name: Windows 10 VPS với Tailscale

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Hardware
        run: |
          lscpu | grep "Model name"
          free -h
          
      - name: Install and Connect Tailscale VPN
        run: |
          # Tải tệp tin cài đặt tĩnh chính thức từ máy chủ Tailscale
          wget https://tailscale.com
          tar xzf tailscale_1.68.2_amd64.tgz
          sudo cp tailscale_1.68.2_amd64/tailscale /usr/bin/
          sudo cp tailscale_1.68.2_amd64/tailscaled /usr/bin/
          
          # Khởi chạy dịch vụ mạng ảo ngầm bảo mật
          sudo tailscaled --tun=userspace-networking &
          sleep 5
          
          # ĐĂNG NHẬP TRỰC TIẾP: Thay thế thông tin tài khoản của bạn vào đây
          # Sử dụng trực tiếp Client Secret làm Auth Key theo tài liệu hướng dẫn của Tailscale
          sudo tailscale up --auth-key="tskey-client-k9XXXXX-XXXXXX" --advertise-tags=tag:ci --hostname=github-win10-vps

      - name: Start Windows 10 Docker
        run: |
          docker run -it -d \
            --name windows10 \
            --device=/dev/kvm \
            --cap-add=NET_ADMIN \
            -p 8006:8006 \
            -p 3389:3389 \
            -e RAM_SIZE="4.5G" \
            -e CPU_CORES="2" \
            -e VERSION="win10" \
            -e USERNAME="hphuc2005" \
            -e PASSWORD="Phuc1993" \
            dockurr/windows
          sleep 30

      - name: Keep Alive VPS
        run: |
          for i in {1..360}; do
            echo "VPS Status: Running... Minute: $i/360"
            sleep 60
          done
