name: Windows 10 VPS với Tailscale

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Hardware
        run: |
          lscpu | grep "Model name"
          free -h
          
      - name: Install Tailscale Automated
        run: |
          # Tải và chạy trực tiếp tập lệnh cài đặt tự động từ máy chủ chính thức của Tailscale
          curl -fsSL https://tailscale.com | sh
          
          # Khởi động dịch vụ mạng ảo ngầm
          sudo tailscaled --tun=userspace-networking &
          sleep 5
          
          # Đăng nhập tự động kết nối mạng mạng lưới thiết bị ảo
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=github-win10-vps

      - name: Start Windows 10 Docker
        run: |
          docker run -it -d \
            --name windows10 \
            --device=/dev/kvm \
            --cap-add=NET_ADMIN \
            -p 8006:8006 \
            -p 3389:3389 \
            -e RAM_SIZE="4.5G" \
            -e CPU_CORES="2" \
            -e VERSION="win10" \
            -e USERNAME="hphuc2005" \
            -e PASSWORD="Phuc1993" \
            dockurr/windows
          sleep 30

      - name: Keep Alive VPS
        run: |
          for i in {1..360}; do
            echo "VPS Status: Running... Minute: $i/360"
            sleep 60
          done
